import type { CitizenAlert, Incident, Resource, Signal } from "./types";

export const CITY = {
  name: "Chennai",
  zone: "Zone 13 · Adyar–Perungudi Corridor",
  citizenWard: "Ward 178 · Velachery East",
  updated: "14:05 IST",
};

export const incidents: Incident[] = [
  {
    id: "i-2431",
    ref: "DS-2431",
    title: "Lake overflow flooding residential blocks",
    hazard: "Urban flood",
    ward: "Ward 178",
    locality: "Velachery East · Taramani Link Road",
    coords: { x: 38, y: 44 },
    priority: "P1",
    priorityRationale: [
      "Risk score 86 with water level rising 6 cm in the last 30 minutes.",
      "12,400 residents exposed, including 2 low-lying tenement blocks.",
      "A 240-bed hospital and 1 primary school sit inside the 300 m impact ring.",
      "Only one road out of the ward is still passable.",
    ],
    stage: "Recommend",
    status: "open",
    confidence: 91,
    riskScore: 86,
    populationExposed: 12400,
    vulnerable: [
      "Velachery Govt. Hospital (240 beds)",
      "Corporation Primary School, 4th Cross",
      "MTC bus depot (ground level)",
    ],
    detectedAt: "11:42",
    detectionSource: "Automated lake gauge exceedance (VLK-03) + rainfall nowcast",
    summary:
      "Velachery lake crossed its full tank level at 11:42 after 96 mm of rain in 3 hours. Overflow is entering 4th and 6th Cross Street through the eastern bund. Depth is increasing and two arterial roads are impassable.",
    rainfallMm: [8, 14, 22, 31, 44, 52],
    waterLevelCm: [12, 18, 26, 34, 41, 47],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "IMD automatic rain gauge · Velachery",
        summary: "96 mm rainfall in 3 hours (red category)",
        detail:
          "Station VLC-AWS reported 52 mm in the last hour alone. Station last calibrated 4 days ago.",
        reliability: 0.96,
        weight: 0.34,
        at: "13:55",
      },
      {
        id: "e2",
        kind: "official",
        source: "Lake level gauge VLK-03",
        summary: "Water level 47 cm above full tank level, rising 6 cm / 30 min",
        detail: "Continuous telemetry, 5-minute interval. No sensor dropouts in the last 12 hours.",
        reliability: 0.94,
        weight: 0.28,
        at: "14:02",
      },
      {
        id: "e3",
        kind: "citizen",
        source: "31 citizen reports from 3 streets",
        summary: "Knee-deep water reported consistently across reporters",
        detail:
          "31 reports clustered within a 400 m radius over 70 minutes. Median reported depth 55 cm. 4 reports were duplicates and excluded.",
        reliability: 0.72,
        weight: 0.18,
        at: "13:48",
      },
      {
        id: "e4",
        kind: "image",
        source: "Citizen photograph · 4th Cross Street",
        summary: "Image classifier: standing water, vehicle half-submerged (high agreement)",
        detail:
          "Two independent photos taken 12 minutes apart show water above the wheel arch of a parked car, giving an estimated depth band of 45–60 cm. Reference objects used: car wheel, kerb, compound gate.",
        reliability: 0.81,
        weight: 0.14,
        at: "13:31",
      },
      {
        id: "e5",
        kind: "gis",
        source: "Corporation drainage & elevation layer",
        summary: "Affected blocks sit 1.2 m below the surrounding road crown",
        detail:
          "Storm-water outfall SW-14 is downstream of the overflow point and already at capacity, so natural drainage is unlikely within 6 hours.",
        reliability: 0.9,
        weight: 0.1,
        at: "12:10",
      },
      {
        id: "e6",
        kind: "official",
        source: "Field patrol unit RTO-2",
        summary: "Patrol reported the eastern bund road as 'passable with care' at 13:20",
        detail:
          "This conflicts with citizen reports of impassable water on the same stretch 20 minutes later. The patrol observation is older and has been down-weighted rather than discarded.",
        reliability: 0.88,
        weight: -0.08,
        at: "13:20",
        conflicting: true,
      },
      {
        id: "e7",
        kind: "historical",
        source: "2015 & 2021 flood extent archive",
        summary: "Same blocks flooded in both previous events at lower rainfall totals",
        detail: "Historical recurrence supports the current extent estimate.",
        reliability: 0.85,
        weight: 0.06,
        at: "—",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Anitha S.",
        text: "Water entered the ground floor of our building. Two elderly residents cannot walk out.",
        ward: "Ward 178",
        at: "13:12",
        hasPhoto: true,
        photoNote: "Stairwell with water at 3rd step",
        waterDepthCm: 55,
        state: "verified",
      },
      {
        id: "r2",
        by: "Karthik R.",
        text: "4th Cross is completely blocked, autos are turning back.",
        ward: "Ward 178",
        at: "13:31",
        hasPhoto: true,
        photoNote: "Car half submerged near junction",
        waterDepthCm: 50,
        state: "verified",
      },
      {
        id: "r3",
        by: "Anonymous",
        text: "Water in our street too",
        ward: "Ward 178",
        at: "13:44",
        hasPhoto: false,
        state: "duplicate",
      },
      {
        id: "r4",
        by: "Fatima B.",
        text: "School children are waiting inside the school, road outside is flooded.",
        ward: "Ward 178",
        at: "13:52",
        hasPhoto: true,
        photoNote: "School gate, water above kerb",
        waterDepthCm: 40,
        state: "matched",
      },
    ],
    timeline: [
      {
        id: "t1",
        at: "11:42",
        stage: "Detect",
        actor: "System",
        text: "Lake gauge VLK-03 exceeded full tank level; incident opened automatically.",
      },
      {
        id: "t2",
        at: "12:26",
        stage: "Verify",
        actor: "System + K. Varma",
        text: "Rainfall telemetry and 11 citizen reports corroborated the signal. Confidence 74%.",
      },
      {
        id: "t3",
        at: "13:31",
        stage: "Verify",
        actor: "System",
        text: "Photo evidence classified as standing water 45–60 cm. Confidence raised to 91%.",
      },
      {
        id: "t4",
        at: "13:40",
        stage: "Assess",
        actor: "System",
        text: "Risk 86/100 — hazard severity 82, human impact 89, drainage recovery poor.",
      },
      {
        id: "t5",
        at: "13:46",
        stage: "Prioritize",
        actor: "System",
        text: "Ranked P1 above DS-2425 due to exposure of a hospital and rising rate of change.",
      },
      {
        id: "t6",
        at: "13:58",
        stage: "Recommend",
        actor: "System",
        text: "Response package drafted and sent for authority approval.",
      },
    ],
    factors: [
      {
        label: "Rainfall intensity",
        detail: "52 mm in the last hour against a 30 mm red threshold",
        value: 88,
        weight: 0.22,
      },
      {
        label: "Rate of change",
        detail: "Water level rising 6 cm per 30 min, no plateau yet",
        value: 84,
        weight: 0.18,
      },
      {
        label: "Population exposure",
        detail: "12,400 residents inside the modelled extent",
        value: 91,
        weight: 0.22,
      },
      {
        label: "Vulnerability",
        detail: "Hospital, school and two tenement blocks inside the impact ring",
        value: 87,
        weight: 0.18,
      },
      {
        label: "Drainage recovery",
        detail: "Outfall SW-14 at capacity; unlikely to clear within 6 hours",
        value: 79,
        weight: 0.12,
      },
      {
        label: "Evidence confidence",
        detail: "91% verified across official, citizen and image sources",
        value: 91,
        weight: 0.08,
      },
    ],
    recommendation: {
      headline: "Evacuate low-lying blocks and open the nearest shelter",
      rationale:
        "Water is still rising and the only remaining exit road is expected to close within the hour. Evacuating before that point avoids a boat-based rescue for roughly 900 residents.",
      actions: [
        "Evacuate 4th and 6th Cross tenement blocks (≈900 residents) to St. Joseph Higher Secondary shelter",
        "Deploy NDRF Team 14 with two inflatable boats to the eastern bund",
        "Place Velachery Govt. Hospital on flood-watch and move ground-floor patients",
        "Issue a critical alert to Ward 178 with the shelter route",
      ],
      status: "pending",
    },
    assigned: ["res-ndrf14"],
    alertIssued: false,
  },
  {
    id: "i-2428",
    ref: "DS-2428",
    title: "Subway inundation trapping vehicles",
    hazard: "Urban flood",
    ward: "Ward 182",
    locality: "Mudichur Road subway",
    coords: { x: 62, y: 30 },
    priority: "P1",
    priorityRationale: [
      "Immediate life risk: vehicles stalled inside a rapidly filling subway.",
      "Confined location with a single access ramp.",
    ],
    stage: "Respond",
    status: "open",
    confidence: 88,
    riskScore: 78,
    populationExposed: 1200,
    vulnerable: ["Subway underpass (no pumping backup)", "Adjacent bus stop"],
    detectedAt: "12:58",
    detectionSource: "Traffic control notification + 9 citizen reports",
    summary:
      "The Mudichur Road subway filled to roughly 1.4 m after pump failure. Two vehicles stalled inside; occupants moved to the ramp. Response is active on site.",
    rainfallMm: [6, 11, 19, 26, 33, 38],
    waterLevelCm: [30, 55, 80, 105, 125, 140],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "Corporation pump station log",
        summary: "Subway pump P-7 offline since 12:31",
        detail: "Power failure logged at the pump house; diesel backup did not start.",
        reliability: 0.93,
        weight: 0.3,
        at: "12:31",
      },
      {
        id: "e2",
        kind: "citizen",
        source: "9 citizen reports",
        summary: "Consistent reports of vehicles stalled inside the subway",
        detail: "Reports clustered within 200 m over 25 minutes.",
        reliability: 0.74,
        weight: 0.24,
        at: "13:04",
      },
      {
        id: "e3",
        kind: "image",
        source: "Citizen photograph · subway ramp",
        summary: "Image classifier: deep water, vehicle roof visible",
        detail: "Estimated depth band 1.2–1.6 m using the ramp railing as reference.",
        reliability: 0.83,
        weight: 0.2,
        at: "13:07",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Suresh M.",
        text: "Two cars stuck in the subway, water rising fast.",
        ward: "Ward 182",
        at: "13:04",
        hasPhoto: true,
        photoNote: "Subway entrance with submerged car",
        waterDepthCm: 140,
        state: "verified",
      },
    ],
    timeline: [
      { id: "t1", at: "12:58", stage: "Detect", actor: "System", text: "Traffic control flagged the subway closure." },
      { id: "t2", at: "13:09", stage: "Verify", actor: "K. Varma", text: "Verified against pump failure log and photos." },
      { id: "t3", at: "13:15", stage: "Prioritize", actor: "System", text: "Ranked P1 — confined space with life risk." },
      { id: "t4", at: "13:22", stage: "Approve", actor: "A. Raman", text: "Rescue package approved without modification." },
      { id: "t5", at: "13:38", stage: "Respond", actor: "Fire & Rescue 03", text: "On site; two occupants moved to safety." },
    ],
    factors: [
      { label: "Life risk", detail: "Occupants in a confined flooding space", value: 95, weight: 0.3 },
      { label: "Water depth", detail: "1.4 m and rising while pumps are offline", value: 86, weight: 0.24 },
      { label: "Population exposure", detail: "1,200 in the immediate corridor", value: 52, weight: 0.2 },
      { label: "Infrastructure failure", detail: "Pump P-7 offline, no working backup", value: 80, weight: 0.16 },
      { label: "Evidence confidence", detail: "88% across three source types", value: 88, weight: 0.1 },
    ],
    recommendation: {
      headline: "Rescue occupants and barricade both subway approaches",
      rationale: "Confined-space flooding carries the highest immediate life risk in the zone.",
      actions: [
        "Fire & Rescue 03 to extract occupants",
        "Barricade both approaches and divert traffic via Tambaram Main Road",
        "Restore pump P-7 with a mobile generator",
      ],
      status: "approved",
      decidedBy: "A. Raman",
    },
    assigned: ["res-fire03", "res-amb11"],
    alertIssued: true,
    responseMinutes: 24,
  },
  {
    id: "i-2425",
    ref: "DS-2425",
    title: "Stormwater backflow into service lanes",
    hazard: "Urban flood",
    ward: "Ward 195",
    locality: "Perungudi · OMR service road",
    coords: { x: 74, y: 58 },
    priority: "P2",
    priorityRationale: [
      "Risk score 61 — property impact, no reported life risk.",
      "Water level stable for the last 40 minutes.",
    ],
    stage: "Monitor",
    status: "monitoring",
    confidence: 82,
    riskScore: 61,
    populationExposed: 5400,
    vulnerable: ["Ground-floor commercial units", "Two IT park access roads"],
    detectedAt: "12:15",
    detectionSource: "Drainage telemetry + 14 citizen reports",
    summary:
      "Backflow from an overloaded stormwater line is pooling in the OMR service lanes. Depth has held at 25–30 cm for 40 minutes while pumping continues.",
    rainfallMm: [5, 9, 15, 20, 24, 26],
    waterLevelCm: [10, 18, 24, 28, 29, 28],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "Drainage telemetry node SW-22",
        summary: "Line running at 104% capacity, level now flat",
        detail: "Flow has plateaued since 13:20, indicating pumping is keeping pace.",
        reliability: 0.91,
        weight: 0.3,
        at: "13:50",
      },
      {
        id: "e2",
        kind: "citizen",
        source: "14 citizen reports",
        summary: "Ankle to knee-deep water on the service lane",
        detail: "Reported depths range 20–35 cm; spread is consistent with a flat pool.",
        reliability: 0.7,
        weight: 0.2,
        at: "13:35",
      },
      {
        id: "e3",
        kind: "gis",
        source: "Land-use layer",
        summary: "Mostly commercial frontage, low residential density",
        detail: "Reduces the human-impact component of the risk score.",
        reliability: 0.88,
        weight: 0.08,
        at: "12:20",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Deepa N.",
        text: "Service road near the IT park is flooded, two-wheelers stalling.",
        ward: "Ward 195",
        at: "13:35",
        hasPhoto: true,
        photoNote: "Service lane with standing water",
        waterDepthCm: 28,
        state: "verified",
      },
    ],
    timeline: [
      { id: "t1", at: "12:15", stage: "Detect", actor: "System", text: "Telemetry flagged line SW-22 over capacity." },
      { id: "t2", at: "12:44", stage: "Verify", actor: "System", text: "Citizen reports corroborated. Confidence 82%." },
      { id: "t3", at: "13:02", stage: "Prioritize", actor: "K. Varma", text: "Held at P2 — property impact only." },
      { id: "t4", at: "13:28", stage: "Respond", actor: "Pump Crew 5", text: "Two mobile pumps deployed." },
      { id: "t5", at: "13:55", stage: "Monitor", actor: "System", text: "Level flat for 40 minutes; watching for reversal." },
    ],
    factors: [
      { label: "Water depth", detail: "28 cm, stable", value: 48, weight: 0.22 },
      { label: "Rate of change", detail: "No rise in 40 minutes", value: 22, weight: 0.18 },
      { label: "Population exposure", detail: "5,400 largely non-residential", value: 55, weight: 0.22 },
      { label: "Vulnerability", detail: "Commercial frontage, no critical facility", value: 40, weight: 0.18 },
      { label: "Drainage recovery", detail: "Pumping keeping pace with inflow", value: 45, weight: 0.12 },
      { label: "Evidence confidence", detail: "82% across two source types", value: 82, weight: 0.08 },
    ],
    recommendation: {
      headline: "Continue pumping and keep the incident under monitoring",
      rationale: "No life risk and a stable level; escalation is not justified while pumps keep pace.",
      actions: [
        "Retain Pump Crew 5 on site for 2 more hours",
        "Advisory alert to Ward 195 commuters",
        "Re-assess if depth exceeds 40 cm",
      ],
      status: "approved",
      decidedBy: "K. Varma",
    },
    assigned: ["res-pump5"],
    alertIssued: true,
    responseMinutes: 47,
  },
  {
    id: "i-2419",
    ref: "DS-2419",
    title: "Reported waterlogging with conflicting evidence",
    hazard: "Urban flood",
    ward: "Ward 121",
    locality: "T. Nagar · Ranganathan Street",
    coords: { x: 24, y: 22 },
    priority: "P3",
    priorityRationale: [
      "Confidence only 46% — official telemetry does not support the citizen reports.",
      "Awaiting field verification before priority is set.",
    ],
    stage: "Verify",
    status: "open",
    confidence: 46,
    riskScore: 38,
    populationExposed: 3100,
    vulnerable: ["Dense market frontage"],
    detectedAt: "13:20",
    detectionSource: "Citizen report cluster",
    summary:
      "Six citizen reports describe waterlogging on Ranganathan Street, but the nearest gauge shows no exceedance and one photograph appears to be from a previous event. Field verification has been requested.",
    rainfallMm: [3, 5, 7, 9, 11, 12],
    waterLevelCm: [4, 6, 8, 9, 10, 10],
    evidence: [
      {
        id: "e1",
        kind: "citizen",
        source: "6 citizen reports",
        summary: "Reports of ankle-deep water across two blocks",
        detail: "Reports are spread over 900 m, which is wider than a typical single pooling event.",
        reliability: 0.62,
        weight: 0.2,
        at: "13:36",
      },
      {
        id: "e2",
        kind: "official",
        source: "Gauge TN-11",
        summary: "No exceedance recorded; rainfall 12 mm in 3 hours",
        detail: "Gauge is 700 m from the reported location and functioning normally.",
        reliability: 0.92,
        weight: -0.22,
        at: "13:58",
        conflicting: true,
      },
      {
        id: "e3",
        kind: "image",
        source: "Citizen photograph",
        summary: "Image metadata suggests the photo predates today's rainfall",
        detail:
          "Classifier detected standing water, but capture time and dry surroundings in the frame are inconsistent with the report. Excluded from the confidence calculation and flagged for review.",
        reliability: 0.35,
        weight: -0.12,
        at: "13:41",
        conflicting: true,
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Ravi P.",
        text: "Water collecting near the market entrance.",
        ward: "Ward 121",
        at: "13:36",
        hasPhoto: true,
        photoNote: "Market entrance, shallow water",
        waterDepthCm: 12,
        state: "queued",
      },
    ],
    timeline: [
      { id: "t1", at: "13:20", stage: "Detect", actor: "System", text: "Report cluster opened a provisional incident." },
      {
        id: "t2",
        at: "13:58",
        stage: "Verify",
        actor: "System",
        text: "Gauge TN-11 contradicts reports; confidence reduced to 46%. Field check requested.",
      },
    ],
    factors: [
      { label: "Rainfall intensity", detail: "12 mm in 3 hours — below threshold", value: 22, weight: 0.22 },
      { label: "Rate of change", detail: "Flat gauge reading", value: 15, weight: 0.18 },
      { label: "Population exposure", detail: "3,100 in a dense market area", value: 62, weight: 0.22 },
      { label: "Vulnerability", detail: "Crowded pedestrian frontage", value: 55, weight: 0.18 },
      { label: "Drainage recovery", detail: "Local drains reported clear", value: 30, weight: 0.12 },
      { label: "Evidence confidence", detail: "46% — conflicting sources", value: 46, weight: 0.08 },
    ],
    recommendation: {
      headline: "Hold response; send a field patrol to confirm or close",
      rationale:
        "Acting on unverified reports would divert a crew from an active P1. A 15-minute field check resolves the conflict.",
      actions: [
        "Dispatch field patrol RTO-2 for visual confirmation",
        "Ask the reporter for a fresh photograph with a timestamp",
        "Close the incident if no water is observed by 15:00",
      ],
      status: "pending",
    },
    assigned: [],
    alertIssued: false,
  },
  {
    id: "i-2413",
    ref: "DS-2413",
    title: "Blocked drain causing localised pooling",
    hazard: "Urban flood",
    ward: "Ward 176",
    locality: "Kotturpuram · Gandhi Nagar 2nd Main",
    coords: { x: 48, y: 70 },
    priority: "P3",
    priorityRationale: ["Low exposure, shallow water, no critical facility affected."],
    stage: "Respond",
    status: "open",
    confidence: 79,
    riskScore: 31,
    populationExposed: 800,
    vulnerable: ["One residential lane"],
    detectedAt: "12:40",
    detectionSource: "Citizen reports (4)",
    summary:
      "A blocked drain is pooling water at the 2nd Main junction. A corporation crew is clearing the inlet.",
    rainfallMm: [4, 7, 10, 13, 16, 18],
    waterLevelCm: [8, 12, 15, 17, 18, 17],
    evidence: [
      {
        id: "e1",
        kind: "citizen",
        source: "4 citizen reports",
        summary: "Consistent reports of pooling at one junction",
        detail: "All four reports fall within 120 m.",
        reliability: 0.75,
        weight: 0.26,
        at: "12:52",
      },
      {
        id: "e2",
        kind: "gis",
        source: "Drain asset register",
        summary: "Inlet KTR-8 last cleared 9 months ago",
        detail: "Maintenance backlog supports the blockage hypothesis.",
        reliability: 0.86,
        weight: 0.12,
        at: "12:45",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Meera J.",
        text: "Drain blocked at the junction, water not draining at all.",
        ward: "Ward 176",
        at: "12:52",
        hasPhoto: true,
        photoNote: "Junction with pooled water",
        waterDepthCm: 17,
        state: "verified",
      },
    ],
    timeline: [
      { id: "t1", at: "12:40", stage: "Detect", actor: "System", text: "Report cluster opened the incident." },
      { id: "t2", at: "12:58", stage: "Verify", actor: "System", text: "Confidence 79% from reports and asset records." },
      { id: "t3", at: "13:10", stage: "Approve", actor: "K. Varma", text: "Maintenance crew approved." },
      { id: "t4", at: "13:26", stage: "Respond", actor: "Corporation Crew 9", text: "Crew on site clearing inlet KTR-8." },
    ],
    factors: [
      { label: "Water depth", detail: "17 cm at one junction", value: 30, weight: 0.22 },
      { label: "Rate of change", detail: "Level receding slowly", value: 18, weight: 0.18 },
      { label: "Population exposure", detail: "800 residents on one lane", value: 25, weight: 0.22 },
      { label: "Vulnerability", detail: "No critical facility in range", value: 20, weight: 0.18 },
      { label: "Drainage recovery", detail: "Clearing in progress", value: 35, weight: 0.12 },
      { label: "Evidence confidence", detail: "79%", value: 79, weight: 0.08 },
    ],
    recommendation: {
      headline: "Clear inlet KTR-8 and close once water recedes",
      rationale: "Routine maintenance response is sufficient at this risk level.",
      actions: ["Corporation Crew 9 to clear the inlet", "Re-check at 15:30 before closing"],
      status: "approved",
      decidedBy: "K. Varma",
    },
    assigned: ["res-crew9"],
    alertIssued: false,
    responseMinutes: 46,
  },
  {
    id: "i-2402",
    ref: "DS-2402",
    title: "Riverside bund seepage",
    hazard: "Urban flood",
    ward: "Ward 170",
    locality: "Adyar riverside · Kasturba Nagar",
    coords: { x: 30, y: 62 },
    priority: "P2",
    priorityRationale: ["Contained after sandbagging; no residential ingress."],
    stage: "Resolve",
    status: "resolved",
    confidence: 93,
    riskScore: 22,
    populationExposed: 2100,
    vulnerable: ["Riverside walkway"],
    detectedAt: "09:05",
    detectionSource: "Field patrol observation",
    summary:
      "Seepage through the Adyar bund was contained by sandbagging. No water entered residential blocks. Incident closed at 12:20.",
    rainfallMm: [10, 12, 9, 6, 4, 2],
    waterLevelCm: [24, 26, 22, 16, 10, 6],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "Field patrol RTO-2",
        summary: "Seepage confirmed visually at 09:05",
        detail: "Patrol photographs and a written observation report.",
        reliability: 0.9,
        weight: 0.4,
        at: "09:05",
      },
      {
        id: "e2",
        kind: "historical",
        source: "Bund maintenance history",
        summary: "Same section seeped in 2021 and was repaired",
        detail: "Known weak point on the bund.",
        reliability: 0.84,
        weight: 0.14,
        at: "—",
      },
    ],
    reports: [],
    timeline: [
      { id: "t1", at: "09:05", stage: "Detect", actor: "RTO-2", text: "Patrol reported seepage at the bund." },
      { id: "t2", at: "09:30", stage: "Verify", actor: "K. Varma", text: "Verified from patrol photographs." },
      { id: "t3", at: "10:02", stage: "Approve", actor: "A. Raman", text: "Sandbagging package approved." },
      { id: "t4", at: "11:40", stage: "Respond", actor: "Corporation Crew 4", text: "Sandbagging completed." },
      { id: "t5", at: "12:20", stage: "Resolve", actor: "A. Raman", text: "Incident resolved; bund holding." },
      {
        id: "t6",
        at: "12:35",
        stage: "Learn",
        actor: "System",
        text: "Added to the repeat-weakness register for pre-monsoon works.",
      },
    ],
    factors: [
      { label: "Water depth", detail: "Contained at the bund face", value: 20, weight: 0.22 },
      { label: "Rate of change", detail: "Receding since 10:00", value: 12, weight: 0.18 },
      { label: "Population exposure", detail: "2,100 behind the bund", value: 45, weight: 0.22 },
      { label: "Vulnerability", detail: "No ingress to housing", value: 18, weight: 0.18 },
      { label: "Drainage recovery", detail: "River level falling", value: 15, weight: 0.12 },
      { label: "Evidence confidence", detail: "93%", value: 93, weight: 0.08 },
    ],
    recommendation: {
      headline: "Sandbag the seepage line and monitor for 3 hours",
      rationale: "Early containment prevents a much larger bund failure.",
      actions: ["Sandbag the 40 m seepage line", "Hold a crew nearby for 3 hours"],
      status: "approved",
      decidedBy: "A. Raman",
    },
    assigned: [],
    alertIssued: true,
    responseMinutes: 57,
    resolutionSummary:
      "Contained in 3h 15m with one crew. Repeat weak point at the same bund chainage as 2021 — flagged for pre-monsoon reinforcement. No injuries, no property damage reported.",
  },
];

export const resources: Resource[] = [
  {
    id: "res-ndrf14",
    name: "NDRF Team 14",
    kind: "team",
    org: "National Disaster Response Force",
    base: "Arakkonam staging",
    coords: { x: 42, y: 40 },
    status: "assigned",
    incidentId: "i-2431",
    crew: 24,
    etaMin: 18,
    route: "GST Road → Taramani Link Road (Velachery bypass flooded)",
  },
  {
    id: "res-fire03",
    name: "Fire & Rescue 03",
    kind: "team",
    org: "TN Fire & Rescue Services",
    base: "Tambaram station",
    coords: { x: 60, y: 33 },
    status: "on_site",
    incidentId: "i-2428",
    crew: 8,
    route: "Tambaram Main Road → Mudichur Road",
  },
  {
    id: "res-crew9",
    name: "Corporation Crew 9",
    kind: "team",
    org: "Greater Chennai Corporation",
    base: "Kotturpuram depot",
    coords: { x: 47, y: 68 },
    status: "on_site",
    incidentId: "i-2413",
    crew: 6,
  },
  {
    id: "res-pump5",
    name: "Pump Crew 5",
    kind: "team",
    org: "Greater Chennai Corporation",
    base: "Perungudi depot",
    coords: { x: 72, y: 56 },
    status: "on_site",
    incidentId: "i-2425",
    crew: 5,
  },
  {
    id: "res-rto2",
    name: "Field Patrol RTO-2",
    kind: "team",
    org: "Revenue & Disaster Management",
    base: "Zone 13 office",
    coords: { x: 35, y: 30 },
    status: "available",
    crew: 3,
  },
  {
    id: "res-amb11",
    name: "Ambulance MDT-11",
    kind: "vehicle",
    org: "108 Emergency Services",
    base: "Tambaram",
    coords: { x: 58, y: 36 },
    status: "en_route",
    incidentId: "i-2428",
    etaMin: 7,
    route: "Tambaram → Mudichur Road subway ramp",
  },
  {
    id: "res-boat2",
    name: "Rescue Boat Unit 2",
    kind: "vehicle",
    org: "TN Fire & Rescue Services",
    base: "Velachery station",
    coords: { x: 40, y: 48 },
    status: "available",
  },
  {
    id: "res-boat3",
    name: "Rescue Boat Unit 3",
    kind: "vehicle",
    org: "TN Fire & Rescue Services",
    base: "Adyar station",
    coords: { x: 31, y: 58 },
    status: "available",
  },
  {
    id: "res-hosp-vel",
    name: "Velachery Govt. Hospital",
    kind: "hospital",
    org: "Directorate of Medical Services",
    base: "Ward 178",
    coords: { x: 36, y: 46 },
    status: "available",
    capacityLabel: "beds",
    capacityUsed: 186,
    capacityTotal: 240,
  },
  {
    id: "res-hosp-tam",
    name: "Tambaram Medical Centre",
    kind: "hospital",
    org: "Directorate of Medical Services",
    base: "Ward 182",
    coords: { x: 64, y: 26 },
    status: "available",
    capacityLabel: "beds",
    capacityUsed: 92,
    capacityTotal: 180,
  },
  {
    id: "res-shelter-stj",
    name: "St. Joseph HSS Shelter",
    kind: "shelter",
    org: "Greater Chennai Corporation",
    base: "Ward 178",
    coords: { x: 44, y: 50 },
    status: "available",
    capacityLabel: "people",
    capacityUsed: 128,
    capacityTotal: 600,
  },
  {
    id: "res-shelter-cmm",
    name: "Corporation Community Hall",
    kind: "shelter",
    org: "Greater Chennai Corporation",
    base: "Ward 195",
    coords: { x: 70, y: 62 },
    status: "available",
    capacityLabel: "people",
    capacityUsed: 64,
    capacityTotal: 350,
  },
];

export const alerts: CitizenAlert[] = [
  {
    id: "a1",
    incidentId: "i-2428",
    level: "critical",
    title: "Mudichur Road subway closed — do not enter",
    area: "Ward 182 · Mudichur Road",
    body: "The subway is flooded to roughly 1.4 m and pumps are offline. Rescue teams are on site.",
    action: "Use Tambaram Main Road instead. Do not attempt to drive through standing water.",
    at: "13:26",
    acknowledged: false,
  },
  {
    id: "a2",
    incidentId: "i-2431",
    level: "warning",
    title: "Rising water in Velachery East",
    area: "Ward 178 · Velachery East",
    body: "Velachery lake has crossed its full tank level and water is entering 4th and 6th Cross Street.",
    action: "Move valuables and documents above floor level. Be ready to leave if asked.",
    at: "12:40",
    acknowledged: false,
  },
  {
    id: "a3",
    incidentId: "i-2425",
    level: "watch",
    title: "Waterlogging advisory — OMR service lanes",
    area: "Ward 195 · Perungudi",
    body: "Standing water of 25–30 cm on the service lanes. Pumping is under way.",
    action: "Avoid two-wheeler travel on the service road for the next two hours.",
    at: "13:05",
    acknowledged: true,
  },
];

export const signals: Signal[] = [
  {
    id: "s1",
    label: "Rainfall spike · Ward 188 (Pallikaranai)",
    detail: "38 mm in 40 minutes with 3 early citizen mentions. No gauge exceedance yet.",
    ward: "Ward 188",
    strength: 64,
    sources: 3,
    at: "14:01",
  },
  {
    id: "s2",
    label: "Drain load rising · Ward 179 (Guindy)",
    detail: "Telemetry node SW-09 climbed from 61% to 88% capacity in 25 minutes.",
    ward: "Ward 179",
    strength: 51,
    sources: 2,
    at: "13:57",
  },
  {
    id: "s3",
    label: "Report cluster forming · Ward 173 (Saidapet)",
    detail: "4 unlinked citizen reports of 'water on road' within 600 m.",
    ward: "Ward 173",
    strength: 42,
    sources: 4,
    at: "13:49",
  },
];

export const dataSources = [
  {
    name: "IMD rainfall & nowcast",
    kind: "Official weather",
    cadence: "Every 15 minutes",
    reliability: 0.96,
    note: "Automatic weather stations and district nowcasts. Primary trigger for detection.",
  },
  {
    name: "Lake & drain telemetry",
    kind: "Official environmental",
    cadence: "Every 5 minutes",
    reliability: 0.93,
    note: "Corporation gauges on lakes, canals and stormwater lines. Sensor dropouts reduce weight automatically.",
  },
  {
    name: "Citizen reports",
    kind: "Crowd",
    cadence: "Continuous",
    reliability: 0.72,
    note: "Clustered by location and time. Duplicates are merged; a lone report never verifies an incident by itself.",
  },
  {
    name: "Citizen photographs",
    kind: "Image evidence",
    cadence: "Continuous",
    reliability: 0.81,
    note: "A classifier estimates water depth from reference objects. Inconsistent capture time or dry surroundings lowers the weight.",
  },
  {
    name: "GIS & elevation layers",
    kind: "Geospatial",
    cadence: "Static, revised yearly",
    reliability: 0.9,
    note: "Ward boundaries, elevation, drainage assets, hospitals, schools and shelters. Used for exposure modelling.",
  },
  {
    name: "Historical flood archive",
    kind: "Reference",
    cadence: "Per event",
    reliability: 0.85,
    note: "2015, 2021 and 2023 flood extents used to sanity-check modelled extent and recurrence.",
  },
];

export const safetyGuide = {
  before: [
    "Keep documents, medicines and a torch in one waterproof bag near the door.",
    "Save your ward shelter address and the 1077 disaster helpline offline.",
    "Move vehicles out of basements and low-lying parking before heavy rain.",
    "Charge phones and power banks when a warning is issued.",
  ],
  during: [
    "Never walk or drive through moving water — 30 cm is enough to sweep a car.",
    "Switch off the mains supply before water reaches sockets.",
    "Move to the highest safe floor; do not shelter in a basement.",
    "If asked to evacuate, leave immediately and take only essentials.",
  ],
  after: [
    "Do not re-enter a flooded building until the power supply is checked.",
    "Boil or treat all drinking water until the corporation confirms supply is safe.",
    "Photograph damage before cleaning up, for relief claims.",
    "Report blocked drains and damaged roads so they enter the repair register.",
  ],
  contacts: [
    { label: "Disaster helpline", value: "1077" },
    { label: "Ambulance", value: "108" },
    { label: "Fire & Rescue", value: "101" },
    { label: "Corporation control room", value: "1913" },
  ],
};

export const analytics = {
  responseMinutes: [
    { label: "Mon", value: 52 },
    { label: "Tue", value: 47 },
    { label: "Wed", value: 44 },
    { label: "Thu", value: 39 },
    { label: "Fri", value: 41 },
    { label: "Sat", value: 34 },
    { label: "Sun", value: 31 },
  ],
  volume: [
    { label: "08:00", value: 2 },
    { label: "09:00", value: 3 },
    { label: "10:00", value: 4 },
    { label: "11:00", value: 6 },
    { label: "12:00", value: 9 },
    { label: "13:00", value: 14 },
    { label: "14:00", value: 11 },
  ],
  verification: {
    autoVerified: 62,
    humanVerified: 27,
    rejected: 11,
    falsePositiveRate: 0.09,
    medianVerifyMinutes: 12,
  },
  seasons: [
    { label: "2021", value: 412 },
    { label: "2022", value: 286 },
    { label: "2023", value: 358 },
    { label: "2024", value: 301 },
    { label: "2025", value: 264 },
  ],
};
