/**
 * DEMO SCENARIO · SIMULATED DATA
 *
 * All incidents, resources, alerts and signals below are fictional.
 * They represent a plausible urban-flood scenario in Kurla West, Mumbai
 * for demonstration and evaluation purposes only.
 *
 * This is NOT live data and does NOT represent any real government operation.
 */

import type { CitizenAlert, Incident, Resource, Signal } from "./types";
import { projectWGS84ToCSS } from "./types";

export const CITY = {
  name: "Mumbai",
  zone: "Kurla West · Mumbai, Maharashtra",
  citizenWard: "Ward L · Kurla West",
  updated: "14:05 IST",
  demoLabel: "DEMO SCENARIO · SIMULATED DATA",
};

export const incidents: Incident[] = [
  {
    id: "i-2431",
    ref: "DS-2431",
    title: "Urban flooding risk in Kurla West",
    hazard: "Urban flood",
    ward: "Ward L",
    locality: "Kurla West · LBS Marg",
    latitude: 19.07680, longitude: 72.87520, coords: projectWGS84ToCSS(19.07680, 72.87520),
    priority: "P1",
    priorityRationale: [
      "Risk score 86 with water level rising 6 cm in the last 30 minutes.",
      "14,200 residents exposed, including 2 low-lying residential clusters.",
      "A 200-bed hospital and 1 municipal school sit inside the 300 m impact ring.",
      "Only one road out of the ward is still passable.",
    ],
    stage: "Recommend",
    incidentStatus: "awaiting_approval",
    status: "open",
    confidence: 91,
    riskScore: 86,
    populationExposed: 14200,
    vulnerable: [
      "Kurla Bhabha Hospital (200 beds)",
      "BMC Municipal School, Nehru Nagar",
      "Kurla bus depot (ground level)",
    ],
    detectedAt: "11:42",
    detectionSource: "Automated drain gauge exceedance (KRL-03) + rainfall nowcast",
    summary:
      "Mithi River tributary nallah overflowed at 11:42 after 112 mm of rain in 3 hours. Water is entering Nehru Nagar and LBS Marg service lanes through the western bund. Depth is increasing and two arterial roads are impassable.",
    rainfallMm: [8, 14, 22, 31, 44, 52],
    waterLevelCm: [12, 18, 26, 34, 41, 47],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "IMD automatic rain gauge · Kurla",
        summary: "112 mm rainfall in 3 hours (red category)",
        detail:
          "Station KRL-AWS reported 52 mm in the last hour alone. Station last calibrated 4 days ago.",
        reliability: 0.96,
        weight: 0.34,
        at: "13:55",
      },
      {
        id: "e2",
        kind: "official",
        source: "Nallah level gauge KRL-03",
        summary: "Water level 47 cm above danger mark, rising 6 cm / 30 min",
        detail: "Continuous telemetry, 5-minute interval. No sensor dropouts in the last 12 hours.",
        reliability: 0.94,
        weight: 0.28,
        at: "14:02",
      },
      {
        id: "e3",
        kind: "citizen",
        source: "31 citizen reports from 3 streets",
        summary: "Knee-deep water reported consistently across reporters",
        detail:
          "31 reports clustered within a 400 m radius over 70 minutes. Median reported depth 55 cm. 4 reports were duplicates and excluded.",
        reliability: 0.72,
        weight: 0.18,
        at: "13:48",
      },
      {
        id: "e4",
        kind: "image",
        source: "Citizen photograph · Nehru Nagar junction",
        summary: "Image classifier: standing water, vehicle half-submerged (high agreement)",
        detail:
          "Two independent photos taken 12 minutes apart show water above the wheel arch of a parked auto-rickshaw, giving an estimated depth band of 45–60 cm.",
        reliability: 0.81,
        weight: 0.14,
        at: "13:31",
      },
      {
        id: "e5",
        kind: "gis",
        source: "BMC drainage & elevation layer",
        summary: "Affected blocks sit 1.2 m below the surrounding road crown",
        detail:
          "Storm-water outfall SW-14 is downstream of the overflow point and already at capacity, so natural drainage is unlikely within 6 hours.",
        reliability: 0.9,
        weight: 0.1,
        at: "12:10",
      },
      {
        id: "e6",
        kind: "official",
        source: "Field patrol unit BMC-2",
        summary: "Patrol reported the western bund road as 'passable with care' at 13:20",
        detail:
          "This conflicts with citizen reports of impassable water on the same stretch 20 minutes later. The patrol observation is older and has been down-weighted rather than discarded.",
        reliability: 0.88,
        weight: -0.08,
        at: "13:20",
        conflicting: true,
      },
      {
        id: "e7",
        kind: "historical",
        source: "2017 & 2020 flood extent archive",
        summary: "Same blocks flooded in both previous events at lower rainfall totals",
        detail: "Historical recurrence supports the current extent estimate.",
        reliability: 0.85,
        weight: 0.06,
        at: "—",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Priya S.",
        text: "Water entered the ground floor of our building. Two elderly residents cannot walk out.",
        ward: "Ward L",
        at: "13:12",
        hasPhoto: true,
        photoNote: "Stairwell with water at 3rd step",
        waterDepthCm: 55,
        state: "verified",
      },
      {
        id: "r2",
        by: "Rajesh K.",
        text: "LBS Marg service lane is completely blocked, autos are turning back.",
        ward: "Ward L",
        at: "13:31",
        hasPhoto: true,
        photoNote: "Auto-rickshaw half submerged near junction",
        waterDepthCm: 50,
        state: "verified",
      },
      {
        id: "r3",
        by: "Anonymous",
        text: "Water in our street too",
        ward: "Ward L",
        at: "13:44",
        hasPhoto: false,
        state: "duplicate",
      },
      {
        id: "r4",
        by: "Fatima B.",
        text: "School children are waiting inside the school, road outside is flooded.",
        ward: "Ward L",
        at: "13:52",
        hasPhoto: true,
        photoNote: "School gate, water above kerb",
        waterDepthCm: 40,
        state: "matched",
      },
    ],
    timeline: [
      {
        id: "t1",
        at: "11:42",
        stage: "Detect",
        actor: "System",
        text: "Nallah gauge KRL-03 exceeded danger mark; incident opened automatically.",
      },
      {
        id: "t2",
        at: "12:26",
        stage: "Verify",
        actor: "System + D. Patil",
        text: "Rainfall telemetry and 11 citizen reports corroborated the signal. Confidence 74%.",
      },
      {
        id: "t3",
        at: "13:31",
        stage: "Verify",
        actor: "System",
        text: "Photo evidence classified as standing water 45–60 cm. Confidence raised to 91%.",
      },
      {
        id: "t4",
        at: "13:40",
        stage: "Assess",
        actor: "System",
        text: "Risk 86/100 — hazard severity 82, human impact 89, drainage recovery poor.",
      },
      {
        id: "t5",
        at: "13:46",
        stage: "Prioritize",
        actor: "System",
        text: "Ranked P1 above DS-2425 due to exposure of a hospital and rising rate of change.",
      },
      {
        id: "t6",
        at: "13:58",
        stage: "Recommend",
        actor: "System",
        text: "Response package drafted and sent for authority approval.",
      },
    ],
    factors: [
      {
        label: "Rainfall intensity",
        detail: "52 mm in the last hour against a 30 mm red threshold",
        value: 88,
        weight: 0.22,
      },
      {
        label: "Rate of change",
        detail: "Water level rising 6 cm per 30 min, no plateau yet",
        value: 84,
        weight: 0.18,
      },
      {
        label: "Population exposure",
        detail: "14,200 residents inside the modelled extent",
        value: 91,
        weight: 0.22,
      },
      {
        label: "Vulnerability",
        detail: "Hospital, school and two residential clusters inside the impact ring",
        value: 87,
        weight: 0.18,
      },
      {
        label: "Drainage recovery",
        detail: "Outfall SW-14 at capacity; unlikely to clear within 6 hours",
        value: 79,
        weight: 0.12,
      },
      {
        label: "Evidence confidence",
        detail: "91% verified across official, citizen and image sources",
        value: 91,
        weight: 0.08,
      },
    ],
    recommendation: {
      headline: "Evacuate low-lying blocks and open the nearest shelter",
      rationale:
        "Water is still rising and the only remaining exit road is expected to close within the hour. Evacuating before that point avoids a boat-based rescue for roughly 1,100 residents.",
      actions: [
        "Evacuate Nehru Nagar residential clusters (≈1,100 residents) to Kurla Community Hall shelter",
        "Deploy NDRF Team 08 with two inflatable boats to the western bund",
        "Place Kurla Bhabha Hospital on flood-watch and move ground-floor patients",
        "Issue a critical alert to Ward L with the shelter route",
      ],
      status: "pending",
    },
    assigned: ["res-ndrf08"],
    alertIssued: false,
  },
  {
    id: "i-2428",
    ref: "DS-2428",
    title: "Subway inundation trapping vehicles",
    hazard: "Urban flood",
    ward: "Ward K/E",
    locality: "Andheri–Kurla Road subway",
    latitude: 19.08100, longitude: 72.88480, coords: projectWGS84ToCSS(19.08100, 72.88480),
    priority: "P1",
    priorityRationale: [
      "Immediate life risk: vehicles stalled inside a rapidly filling subway.",
      "Confined location with a single access ramp.",
    ],
    stage: "Respond",
    incidentStatus: "on_scene",
    status: "open",
    confidence: 88,
    riskScore: 78,
    populationExposed: 1200,
    vulnerable: ["Subway underpass (no pumping backup)", "Adjacent bus stop"],
    detectedAt: "12:58",
    detectionSource: "Traffic police notification + 9 citizen reports",
    summary:
      "The Andheri–Kurla Road subway filled to roughly 1.4 m after pump failure. Two vehicles stalled inside; occupants moved to the ramp. Response is active on site.",
    rainfallMm: [6, 11, 19, 26, 33, 38],
    waterLevelCm: [30, 55, 80, 105, 125, 140],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "BMC pump station log",
        summary: "Subway pump P-7 offline since 12:31",
        detail: "Power failure logged at the pump house; diesel backup did not start.",
        reliability: 0.93,
        weight: 0.3,
        at: "12:31",
      },
      {
        id: "e2",
        kind: "citizen",
        source: "9 citizen reports",
        summary: "Consistent reports of vehicles stalled inside the subway",
        detail: "Reports clustered within 200 m over 25 minutes.",
        reliability: 0.74,
        weight: 0.24,
        at: "13:04",
      },
      {
        id: "e3",
        kind: "image",
        source: "Citizen photograph · subway ramp",
        summary: "Image classifier: deep water, vehicle roof visible",
        detail: "Estimated depth band 1.2–1.6 m using the ramp railing as reference.",
        reliability: 0.83,
        weight: 0.2,
        at: "13:07",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Suresh M.",
        text: "Two cars stuck in the subway, water rising fast.",
        ward: "Ward K/E",
        at: "13:04",
        hasPhoto: true,
        photoNote: "Subway entrance with submerged car",
        waterDepthCm: 140,
        state: "verified",
      },
    ],
    timeline: [
      { id: "t1", at: "12:58", stage: "Detect", actor: "System", text: "Traffic police flagged the subway closure." },
      { id: "t2", at: "13:09", stage: "Verify", actor: "D. Patil", text: "Verified against pump failure log and photos." },
      { id: "t3", at: "13:15", stage: "Prioritize", actor: "System", text: "Ranked P1 — confined space with life risk." },
      { id: "t4", at: "13:22", stage: "Approve", actor: "S. Deshmukh", text: "Rescue package approved without modification." },
      { id: "t5", at: "13:38", stage: "Respond", actor: "Fire Brigade 03", text: "On site; two occupants moved to safety." },
    ],
    factors: [
      { label: "Life risk", detail: "Occupants in a confined flooding space", value: 95, weight: 0.3 },
      { label: "Water depth", detail: "1.4 m and rising while pumps are offline", value: 86, weight: 0.24 },
      { label: "Population exposure", detail: "1,200 in the immediate corridor", value: 52, weight: 0.2 },
      { label: "Infrastructure failure", detail: "Pump P-7 offline, no working backup", value: 80, weight: 0.16 },
      { label: "Evidence confidence", detail: "88% across three source types", value: 88, weight: 0.1 },
    ],
    recommendation: {
      headline: "Rescue occupants and barricade both subway approaches",
      rationale: "Confined-space flooding carries the highest immediate life risk in the zone.",
      actions: [
        "Fire Brigade 03 to extract occupants",
        "Barricade both approaches and divert traffic via SV Road",
        "Restore pump P-7 with a mobile generator",
      ],
      status: "approved",
      decidedBy: "S. Deshmukh",
    },
    assigned: ["res-fire03", "res-amb11"],
    alertIssued: true,
    responseMinutes: 24,
  },
  {
    id: "i-2425",
    ref: "DS-2425",
    title: "Stormwater backflow into service lanes",
    hazard: "Urban flood",
    ward: "Ward K/W",
    locality: "BKC · Bandra–Kurla Complex service road",
    latitude: 19.07260, longitude: 72.88960, coords: projectWGS84ToCSS(19.07260, 72.88960),
    priority: "P2",
    priorityRationale: [
      "Risk score 61 — property impact, no reported life risk.",
      "Water level stable for the last 40 minutes.",
    ],
    stage: "Monitor",
    incidentStatus: "mitigating",
    status: "monitoring",
    confidence: 82,
    riskScore: 61,
    populationExposed: 5400,
    vulnerable: ["Ground-floor commercial units", "Two BKC access roads"],
    detectedAt: "12:15",
    detectionSource: "Drainage telemetry + 14 citizen reports",
    summary:
      "Backflow from an overloaded stormwater line is pooling in the BKC service lanes. Depth has held at 25–30 cm for 40 minutes while pumping continues.",
    rainfallMm: [5, 9, 15, 20, 24, 26],
    waterLevelCm: [10, 18, 24, 28, 29, 28],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "Drainage telemetry node SW-22",
        summary: "Line running at 104% capacity, level now flat",
        detail: "Flow has plateaued since 13:20, indicating pumping is keeping pace.",
        reliability: 0.91,
        weight: 0.3,
        at: "13:50",
      },
      {
        id: "e2",
        kind: "citizen",
        source: "14 citizen reports",
        summary: "Ankle to knee-deep water on the service lane",
        detail: "Reported depths range 20–35 cm; spread is consistent with a flat pool.",
        reliability: 0.7,
        weight: 0.2,
        at: "13:35",
      },
      {
        id: "e3",
        kind: "gis",
        source: "Land-use layer",
        summary: "Mostly commercial frontage, low residential density",
        detail: "Reduces the human-impact component of the risk score.",
        reliability: 0.88,
        weight: 0.08,
        at: "12:20",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Deepa N.",
        text: "Service road near BKC is flooded, two-wheelers stalling.",
        ward: "Ward K/W",
        at: "13:35",
        hasPhoto: true,
        photoNote: "Service lane with standing water",
        waterDepthCm: 28,
        state: "verified",
      },
    ],
    timeline: [
      { id: "t1", at: "12:15", stage: "Detect", actor: "System", text: "Telemetry flagged line SW-22 over capacity." },
      { id: "t2", at: "12:44", stage: "Verify", actor: "System", text: "Citizen reports corroborated. Confidence 82%." },
      { id: "t3", at: "13:02", stage: "Prioritize", actor: "D. Patil", text: "Held at P2 — property impact only." },
      { id: "t4", at: "13:28", stage: "Respond", actor: "Pump Crew 5", text: "Two mobile pumps deployed." },
      { id: "t5", at: "13:55", stage: "Monitor", actor: "System", text: "Level flat for 40 minutes; watching for reversal." },
    ],
    factors: [
      { label: "Water depth", detail: "28 cm, stable", value: 48, weight: 0.22 },
      { label: "Rate of change", detail: "No rise in 40 minutes", value: 22, weight: 0.18 },
      { label: "Population exposure", detail: "5,400 largely non-residential", value: 55, weight: 0.22 },
      { label: "Vulnerability", detail: "Commercial frontage, no critical facility", value: 40, weight: 0.18 },
      { label: "Drainage recovery", detail: "Pumping keeping pace with inflow", value: 45, weight: 0.12 },
      { label: "Evidence confidence", detail: "82% across two source types", value: 82, weight: 0.08 },
    ],
    recommendation: {
      headline: "Continue pumping and keep the incident under monitoring",
      rationale: "No life risk and a stable level; escalation is not justified while pumps keep pace.",
      actions: [
        "Retain Pump Crew 5 on site for 2 more hours",
        "Advisory alert to Ward K/W commuters",
        "Re-assess if depth exceeds 40 cm",
      ],
      status: "approved",
      decidedBy: "D. Patil",
    },
    assigned: ["res-pump5"],
    alertIssued: true,
    responseMinutes: 47,
  },
  {
    id: "i-2419",
    ref: "DS-2419",
    title: "Reported waterlogging with conflicting evidence",
    hazard: "Urban flood",
    ward: "Ward H/W",
    locality: "Dadar · Senapati Bapat Marg",
    latitude: 19.08340, longitude: 72.86960, coords: projectWGS84ToCSS(19.08340, 72.86960),
    priority: "P3",
    priorityRationale: [
      "Confidence only 46% — official telemetry does not support the citizen reports.",
      "Awaiting field verification before priority is set.",
    ],
    stage: "Verify",
    incidentStatus: "verifying",
    status: "open",
    confidence: 46,
    riskScore: 38,
    populationExposed: 3100,
    vulnerable: ["Dense market frontage"],
    detectedAt: "13:20",
    detectionSource: "Citizen report cluster",
    summary:
      "Six citizen reports describe waterlogging on Senapati Bapat Marg, but the nearest gauge shows no exceedance and one photograph appears to be from a previous event. Field verification has been requested.",
    rainfallMm: [3, 5, 7, 9, 11, 12],
    waterLevelCm: [4, 6, 8, 9, 10, 10],
    evidence: [
      {
        id: "e1",
        kind: "citizen",
        source: "6 citizen reports",
        summary: "Reports of ankle-deep water across two blocks",
        detail: "Reports are spread over 900 m, which is wider than a typical single pooling event.",
        reliability: 0.62,
        weight: 0.2,
        at: "13:36",
      },
      {
        id: "e2",
        kind: "official",
        source: "Gauge DD-11",
        summary: "No exceedance recorded; rainfall 12 mm in 3 hours",
        detail: "Gauge is 700 m from the reported location and functioning normally.",
        reliability: 0.92,
        weight: -0.22,
        at: "13:58",
        conflicting: true,
      },
      {
        id: "e3",
        kind: "image",
        source: "Citizen photograph",
        summary: "Image metadata suggests the photo predates today's rainfall",
        detail:
          "Classifier detected standing water, but capture time and dry surroundings in the frame are inconsistent with the report. Excluded from the confidence calculation and flagged for review.",
        reliability: 0.35,
        weight: -0.12,
        at: "13:41",
        conflicting: true,
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Ravi P.",
        text: "Water collecting near the market entrance.",
        ward: "Ward H/W",
        at: "13:36",
        hasPhoto: true,
        photoNote: "Market entrance, shallow water",
        waterDepthCm: 12,
        state: "queued",
      },
    ],
    timeline: [
      { id: "t1", at: "13:20", stage: "Detect", actor: "System", text: "Report cluster opened a provisional incident." },
      {
        id: "t2",
        at: "13:58",
        stage: "Verify",
        actor: "System",
        text: "Gauge DD-11 contradicts reports; confidence reduced to 46%. Field check requested.",
      },
    ],
    factors: [
      { label: "Rainfall intensity", detail: "12 mm in 3 hours — below threshold", value: 22, weight: 0.22 },
      { label: "Rate of change", detail: "Flat gauge reading", value: 15, weight: 0.18 },
      { label: "Population exposure", detail: "3,100 in a dense market area", value: 62, weight: 0.22 },
      { label: "Vulnerability", detail: "Crowded pedestrian frontage", value: 55, weight: 0.18 },
      { label: "Drainage recovery", detail: "Local drains reported clear", value: 30, weight: 0.12 },
      { label: "Evidence confidence", detail: "46% — conflicting sources", value: 46, weight: 0.08 },
    ],
    recommendation: {
      headline: "Hold response; send a field patrol to confirm or close",
      rationale:
        "Acting on unverified reports would divert a crew from an active P1. A 15-minute field check resolves the conflict.",
      actions: [
        "Dispatch field patrol BMC-2 for visual confirmation",
        "Ask the reporter for a fresh photograph with a timestamp",
        "Close the incident if no water is observed by 15:00",
      ],
      status: "pending",
    },
    assigned: [],
    alertIssued: false,
  },
  {
    id: "i-2413",
    ref: "DS-2413",
    title: "Blocked drain causing localised pooling",
    hazard: "Urban flood",
    ward: "Ward L",
    locality: "Kurla West · Nehru Nagar 2nd Lane",
    latitude: 19.06900, longitude: 72.87920, coords: projectWGS84ToCSS(19.06900, 72.87920),
    priority: "P3",
    priorityRationale: ["Low exposure, shallow water, no critical facility affected."],
    stage: "Respond",
    incidentStatus: "on_scene",
    status: "open",
    confidence: 79,
    riskScore: 31,
    populationExposed: 800,
    vulnerable: ["One residential lane"],
    detectedAt: "12:40",
    detectionSource: "Citizen reports (4)",
    summary:
      "A blocked drain is pooling water at the 2nd Lane junction. A BMC crew is clearing the inlet.",
    rainfallMm: [4, 7, 10, 13, 16, 18],
    waterLevelCm: [8, 12, 15, 17, 18, 17],
    evidence: [
      {
        id: "e1",
        kind: "citizen",
        source: "4 citizen reports",
        summary: "Consistent reports of pooling at one junction",
        detail: "All four reports fall within 120 m.",
        reliability: 0.75,
        weight: 0.26,
        at: "12:52",
      },
      {
        id: "e2",
        kind: "gis",
        source: "Drain asset register",
        summary: "Inlet KRL-8 last cleared 9 months ago",
        detail: "Maintenance backlog supports the blockage hypothesis.",
        reliability: 0.86,
        weight: 0.12,
        at: "12:45",
      },
    ],
    reports: [
      {
        id: "r1",
        by: "Meera J.",
        text: "Drain blocked at the junction, water not draining at all.",
        ward: "Ward L",
        at: "12:52",
        hasPhoto: true,
        photoNote: "Junction with pooled water",
        waterDepthCm: 17,
        state: "verified",
      },
    ],
    timeline: [
      { id: "t1", at: "12:40", stage: "Detect", actor: "System", text: "Report cluster opened the incident." },
      { id: "t2", at: "12:58", stage: "Verify", actor: "System", text: "Confidence 79% from reports and asset records." },
      { id: "t3", at: "13:10", stage: "Approve", actor: "D. Patil", text: "Maintenance crew approved." },
      { id: "t4", at: "13:26", stage: "Respond", actor: "BMC Crew 9", text: "Crew on site clearing inlet KRL-8." },
    ],
    factors: [
      { label: "Water depth", detail: "17 cm at one junction", value: 30, weight: 0.22 },
      { label: "Rate of change", detail: "Level receding slowly", value: 18, weight: 0.18 },
      { label: "Population exposure", detail: "800 residents on one lane", value: 25, weight: 0.22 },
      { label: "Vulnerability", detail: "No critical facility in range", value: 20, weight: 0.18 },
      { label: "Drainage recovery", detail: "Clearing in progress", value: 35, weight: 0.12 },
      { label: "Evidence confidence", detail: "79%", value: 79, weight: 0.08 },
    ],
    recommendation: {
      headline: "Clear inlet KRL-8 and close once water recedes",
      rationale: "Routine maintenance response is sufficient at this risk level.",
      actions: ["BMC Crew 9 to clear the inlet", "Re-check at 15:30 before closing"],
      status: "approved",
      decidedBy: "D. Patil",
    },
    assigned: ["res-crew9"],
    alertIssued: false,
    responseMinutes: 46,
  },
  {
    id: "i-2402",
    ref: "DS-2402",
    title: "Mithi riverbank seepage",
    hazard: "Urban flood",
    ward: "Ward K/E",
    locality: "Mithi riverside · Safed Pool",
    latitude: 19.07140, longitude: 72.87200, coords: projectWGS84ToCSS(19.07140, 72.87200),
    priority: "P2",
    priorityRationale: ["Contained after sandbagging; no residential ingress."],
    stage: "Resolve",
    incidentStatus: "resolved",
    status: "resolved",
    confidence: 93,
    riskScore: 22,
    populationExposed: 2100,
    vulnerable: ["Riverside walkway"],
    detectedAt: "09:05",
    detectionSource: "Field patrol observation",
    summary:
      "Seepage through the Mithi riverbank was contained by sandbagging. No water entered residential blocks. Incident closed at 12:20.",
    rainfallMm: [10, 12, 9, 6, 4, 2],
    waterLevelCm: [24, 26, 22, 16, 10, 6],
    evidence: [
      {
        id: "e1",
        kind: "official",
        source: "Field patrol BMC-2",
        summary: "Seepage confirmed visually at 09:05",
        detail: "Patrol photographs and a written observation report.",
        reliability: 0.9,
        weight: 0.4,
        at: "09:05",
      },
      {
        id: "e2",
        kind: "historical",
        source: "Riverbank maintenance history",
        summary: "Same section seeped in 2020 and was repaired",
        detail: "Known weak point on the bank.",
        reliability: 0.84,
        weight: 0.14,
        at: "—",
      },
    ],
    reports: [],
    timeline: [
      { id: "t1", at: "09:05", stage: "Detect", actor: "BMC-2", text: "Patrol reported seepage at the riverbank." },
      { id: "t2", at: "09:30", stage: "Verify", actor: "D. Patil", text: "Verified from patrol photographs." },
      { id: "t3", at: "10:02", stage: "Approve", actor: "S. Deshmukh", text: "Sandbagging package approved." },
      { id: "t4", at: "11:40", stage: "Respond", actor: "BMC Crew 4", text: "Sandbagging completed." },
      { id: "t5", at: "12:20", stage: "Resolve", actor: "S. Deshmukh", text: "Incident resolved; bank holding." },
      {
        id: "t6",
        at: "12:35",
        stage: "Learn",
        actor: "System",
        text: "Added to the repeat-weakness register for pre-monsoon works.",
      },
    ],
    factors: [
      { label: "Water depth", detail: "Contained at the bank face", value: 20, weight: 0.22 },
      { label: "Rate of change", detail: "Receding since 10:00", value: 12, weight: 0.18 },
      { label: "Population exposure", detail: "2,100 behind the bank", value: 45, weight: 0.22 },
      { label: "Vulnerability", detail: "No ingress to housing", value: 18, weight: 0.18 },
      { label: "Drainage recovery", detail: "River level falling", value: 15, weight: 0.12 },
      { label: "Evidence confidence", detail: "93%", value: 93, weight: 0.08 },
    ],
    recommendation: {
      headline: "Sandbag the seepage line and monitor for 3 hours",
      rationale: "Early containment prevents a much larger bank failure.",
      actions: ["Sandbag the 40 m seepage line", "Hold a crew nearby for 3 hours"],
      status: "approved",
      decidedBy: "S. Deshmukh",
    },
    assigned: [],
    alertIssued: true,
    responseMinutes: 57,
    resolution: {
      resolvedAt: "12:20",
      reason: "Seepage contained by sandbagging; no water entered residential blocks.",
      resourcesUsed: ["BMC Crew 4"],
      responderNotes: "Same bank section as 2020 failure. Pre-monsoon reinforcement recommended.",
      impactSummary: "Contained in 3h 15m with one crew. No injuries, no property damage reported.",
      responseMinutes: 57,
    },
    resolutionSummary:
      "Contained in 3h 15m with one crew. Repeat weak point at the same bank chainage as 2020 — flagged for pre-monsoon reinforcement. No injuries, no property damage reported.",
  },
];

/**
 * SIMULATED RESOURCES
 *
 * These are fictional units for demonstration purposes.
 * Types: rescue team, ambulance, medical team, fire response,
 * police/traffic, boat, shelter, relief supplies.
 */
export const resources: Resource[] = [
  {
    id: "res-ndrf08",
    name: "NDRF Team 08",
    kind: "team",
    type: "Rescue Team",
    org: "National Disaster Response Force",
    base: "Andheri staging area",
    latitude: 19.07800, longitude: 72.87680, coords: projectWGS84ToCSS(19.07800, 72.87680),
    status: "assigned",
    incidentId: "i-2431",
    crew: 24,
    etaMin: 18,
    route: "WEH → LBS Marg (Kurla bypass flooded)",
  },
  {
    id: "res-fire03",
    name: "Fire Brigade 03",
    kind: "team",
    type: "Fire Response",
    org: "Mumbai Fire Brigade",
    base: "Kurla station",
    latitude: 19.08010, longitude: 72.88400, coords: projectWGS84ToCSS(19.08010, 72.88400),
    status: "on_site",
    incidentId: "i-2428",
    crew: 8,
    route: "Kurla → Andheri–Kurla Road",
  },
  {
    id: "res-crew9",
    name: "BMC Crew 9",
    kind: "team",
    type: "Maintenance Crew",
    org: "BMC Storm Water Drains",
    base: "Kurla West depot",
    latitude: 19.06960, longitude: 72.87880, coords: projectWGS84ToCSS(19.06960, 72.87880),
    status: "on_site",
    incidentId: "i-2413",
    crew: 6,
  },
  {
    id: "res-pump5",
    name: "Pump Crew 5",
    kind: "team",
    type: "Pump Operations",
    org: "BMC Storm Water Drains",
    base: "BKC depot",
    latitude: 19.07320, longitude: 72.88880, coords: projectWGS84ToCSS(19.07320, 72.88880),
    status: "on_site",
    incidentId: "i-2425",
    crew: 5,
  },
  {
    id: "res-patrol2",
    name: "Field Patrol BMC-2",
    kind: "team",
    type: "Field Patrol",
    org: "BMC Disaster Cell",
    base: "Ward L office",
    latitude: 19.08100, longitude: 72.87400, coords: projectWGS84ToCSS(19.08100, 72.87400),
    status: "available",
    crew: 3,
  },
  {
    id: "res-amb11",
    name: "Ambulance KRL-11",
    kind: "vehicle",
    type: "Ambulance",
    org: "108 Emergency Services",
    base: "Kurla",
    latitude: 19.07920, longitude: 72.88320, coords: projectWGS84ToCSS(19.07920, 72.88320),
    status: "en_route",
    incidentId: "i-2428",
    etaMin: 7,
    route: "Kurla → Andheri–Kurla Road subway ramp",
  },
  {
    id: "res-boat2",
    name: "Rescue Boat Unit 2",
    kind: "boat",
    type: "Rescue Boat",
    org: "Mumbai Fire Brigade",
    base: "Kurla station",
    latitude: 19.07560, longitude: 72.87600, coords: projectWGS84ToCSS(19.07560, 72.87600),
    status: "available",
    crew: 4,
  },
  {
    id: "res-boat3",
    name: "Rescue Boat Unit 3",
    kind: "boat",
    type: "Rescue Boat",
    org: "Mumbai Fire Brigade",
    base: "Sion station",
    latitude: 19.07260, longitude: 72.87240, coords: projectWGS84ToCSS(19.07260, 72.87240),
    status: "available",
    crew: 4,
  },
  {
    id: "res-medical1",
    name: "Medical Response Team 1",
    kind: "team",
    type: "Medical Team",
    org: "BMC Health Department",
    base: "Kurla Bhabha Hospital",
    latitude: 19.07740, longitude: 72.87440, coords: projectWGS84ToCSS(19.07740, 72.87440),
    status: "available",
    crew: 6,
  },
  {
    id: "res-police1",
    name: "Traffic Police Unit T-12",
    kind: "team",
    type: "Police / Traffic",
    org: "Mumbai Traffic Police",
    base: "Kurla traffic chowki",
    latitude: 19.07950, longitude: 72.88000, coords: projectWGS84ToCSS(19.07950, 72.88000),
    status: "available",
    crew: 8,
  },
  {
    id: "res-relief1",
    name: "Relief Supply Kit 4",
    kind: "relief",
    type: "Relief Supplies",
    org: "BMC Disaster Cell",
    base: "Ward L warehouse",
    latitude: 19.07440, longitude: 72.87760, coords: projectWGS84ToCSS(19.07440, 72.87760),
    status: "available",
    capacityLabel: "kits",
    capacityUsed: 0,
    capacityTotal: 500,
  },
  {
    id: "res-hosp-krl",
    name: "Kurla Bhabha Hospital",
    kind: "hospital",
    type: "Hospital",
    org: "BMC Health Department",
    base: "Ward L",
    latitude: 19.07620, longitude: 72.87440, coords: projectWGS84ToCSS(19.07620, 72.87440),
    status: "available",
    capacityLabel: "beds",
    capacityUsed: 156,
    capacityTotal: 200,
  },
  {
    id: "res-hosp-sion",
    name: "Sion Hospital",
    kind: "hospital",
    type: "Hospital",
    org: "BMC Health Department",
    base: "Ward F/N",
    latitude: 19.08220, longitude: 72.88560, coords: projectWGS84ToCSS(19.08220, 72.88560),
    status: "available",
    capacityLabel: "beds",
    capacityUsed: 310,
    capacityTotal: 450,
  },
  {
    id: "res-shelter-cmh",
    name: "Kurla Community Hall Shelter",
    kind: "shelter",
    type: "Emergency Shelter",
    org: "BMC Disaster Cell",
    base: "Ward L",
    latitude: 19.07500, longitude: 72.87760, coords: projectWGS84ToCSS(19.07500, 72.87760),
    status: "available",
    capacityLabel: "people",
    capacityUsed: 128,
    capacityTotal: 600,
  },
  {
    id: "res-shelter-bkc",
    name: "BKC Convention Centre Shelter",
    kind: "shelter",
    type: "Emergency Shelter",
    org: "BMC Disaster Cell",
    base: "Ward K/W",
    latitude: 19.07140, longitude: 72.88800, coords: projectWGS84ToCSS(19.07140, 72.88800),
    status: "available",
    capacityLabel: "people",
    capacityUsed: 64,
    capacityTotal: 350,
  },
];

export const alerts: CitizenAlert[] = [
  {
    id: "a1",
    incidentId: "i-2428",
    level: "critical",
    title: "Andheri–Kurla Road subway closed — do not enter",
    area: "Ward K/E · Andheri–Kurla Road",
    body: "The subway is flooded to roughly 1.4 m and pumps are offline. Rescue teams are on site.",
    action: "Use SV Road instead. Do not attempt to drive through standing water.",
    at: "13:26",
    acknowledged: false,
  },
  {
    id: "a2",
    incidentId: "i-2431",
    level: "warning",
    title: "Rising water in Kurla West",
    area: "Ward L · Kurla West",
    body: "Mithi tributary nallah has overflowed and water is entering Nehru Nagar and LBS Marg service lanes.",
    action: "Move valuables and documents above floor level. Be ready to leave if asked.",
    at: "12:40",
    acknowledged: false,
  },
  {
    id: "a3",
    incidentId: "i-2425",
    level: "watch",
    title: "Waterlogging advisory — BKC service lanes",
    area: "Ward K/W · BKC",
    body: "Standing water of 25–30 cm on the service lanes. Pumping is under way.",
    action: "Avoid two-wheeler travel on the service road for the next two hours.",
    at: "13:05",
    acknowledged: true,
  },
];

export const signals: Signal[] = [
  {
    id: "s1",
    label: "Rainfall spike · Ward G/N (Dharavi)",
    detail: "38 mm in 40 minutes with 3 early citizen mentions. No gauge exceedance yet.",
    ward: "Ward G/N",
    strength: 64,
    sources: 3,
    at: "14:01",
  },
  {
    id: "s2",
    label: "Drain load rising · Ward K/E (Santacruz)",
    detail: "Telemetry node SW-09 climbed from 61% to 88% capacity in 25 minutes.",
    ward: "Ward K/E",
    strength: 51,
    sources: 2,
    at: "13:57",
  },
  {
    id: "s3",
    label: "Report cluster forming · Ward F/N (Sion)",
    detail: "4 unlinked citizen reports of 'water on road' within 600 m.",
    ward: "Ward F/N",
    strength: 42,
    sources: 4,
    at: "13:49",
  },
];

export const dataSources = [
  {
    name: "IMD rainfall & nowcast",
    kind: "Official weather",
    cadence: "Every 15 minutes",
    reliability: 0.96,
    note: "Automatic weather stations and district nowcasts. Primary trigger for detection.",
  },
  {
    name: "Nallah & drain telemetry",
    kind: "Official environmental",
    cadence: "Every 5 minutes",
    reliability: 0.93,
    note: "BMC gauges on nallahs, canals and stormwater lines. Sensor dropouts reduce weight automatically.",
  },
  {
    name: "Citizen reports",
    kind: "Crowd",
    cadence: "Continuous",
    reliability: 0.72,
    note: "Clustered by location and time. Duplicates are merged; a lone report never verifies an incident by itself.",
  },
  {
    name: "Citizen photographs",
    kind: "Image evidence",
    cadence: "Continuous",
    reliability: 0.81,
    note: "A classifier estimates water depth from reference objects. Inconsistent capture time or dry surroundings lowers the weight.",
  },
  {
    name: "GIS & elevation layers",
    kind: "Geospatial",
    cadence: "Static, revised yearly",
    reliability: 0.9,
    note: "Ward boundaries, elevation, drainage assets, hospitals, schools and shelters. Used for exposure modelling.",
  },
  {
    name: "Historical flood archive",
    kind: "Reference",
    cadence: "Per event",
    reliability: 0.85,
    note: "2017, 2020 and 2023 flood extents used to sanity-check modelled extent and recurrence.",
  },
];

export const safetyGuide = {
  before: [
    "Keep documents, medicines and a torch in one waterproof bag near the door.",
    "Save your ward shelter address and the 1916 disaster helpline offline.",
    "Move vehicles out of basements and low-lying parking before heavy rain.",
    "Charge phones and power banks when a warning is issued.",
  ],
  during: [
    "Never walk or drive through moving water — 30 cm is enough to sweep a car.",
    "Switch off the mains supply before water reaches sockets.",
    "Move to the highest safe floor; do not shelter in a basement.",
    "If asked to evacuate, leave immediately and take only essentials.",
  ],
  after: [
    "Do not re-enter a flooded building until the power supply is checked.",
    "Boil or treat all drinking water until BMC confirms supply is safe.",
    "Photograph damage before cleaning up, for relief claims.",
    "Report blocked drains and damaged roads so they enter the repair register.",
  ],
  contacts: [
    { label: "Disaster helpline", value: "1916" },
    { label: "Ambulance", value: "108" },
    { label: "Fire Brigade", value: "101" },
    { label: "BMC control room", value: "1916" },
  ],
};

export const analytics = {
  responseMinutes: [
    { label: "Mon", value: 52 },
    { label: "Tue", value: 47 },
    { label: "Wed", value: 44 },
    { label: "Thu", value: 39 },
    { label: "Fri", value: 41 },
    { label: "Sat", value: 34 },
    { label: "Sun", value: 31 },
  ],
  volume: [
    { label: "08:00", value: 2 },
    { label: "09:00", value: 3 },
    { label: "10:00", value: 4 },
    { label: "11:00", value: 6 },
    { label: "12:00", value: 9 },
    { label: "13:00", value: 14 },
    { label: "14:00", value: 11 },
  ],
  verification: {
    autoVerified: 62,
    humanVerified: 27,
    rejected: 11,
    falsePositiveRate: 0.09,
    medianVerifyMinutes: 12,
  },
  seasons: [
    { label: "2021", value: 412 },
    { label: "2022", value: 286 },
    { label: "2023", value: 358 },
    { label: "2024", value: 301 },
    { label: "2025", value: 264 },
  ],
};
